pipeline {
    agent any

    environment {
        DOCKER_notification  = 'kelompokdealan'
        DOCKER_TOKEN = 'dckr_pat_w0tn8ZmBXAsXwKIGuDNMcM9UYKk'
        IMAGE_NAME   = 'kelompokdealan/notification-service'
        SERVICE_DIR  = 'notification-service'
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Checking out source code from GitHub...'
                git branch: 'main', url: "${GIT_REPO_URL}"
            }
        }

        stage('Unit Tests') {
            steps {
                echo 'Running Unit Tests...'
                bat 'cd /d auth-service && go test -v ./service/...'
            }
        }

        stage('Lint/Vet') {
            steps {
                echo 'Running Go Vet...'
                bat 'cd /d auth-service && go vet ./...'
            }
        }

        stage('Docker Login') {
            steps {
                echo 'Logging in to Docker Hub securely...'
                // Pastikan kalian sudah membuat credential dengan ID 'docker-baru' di Jenkins kalian
                withCredentials([usernamePassword(
                    credentialsId: 'docker-baru',
                    usernameVariable: 'D_USER',
                    passwordVariable: 'D_PASS'
                )]) {
                    bat 'docker login -u %D_USER% -p %D_PASS%'
                }
            }
        }

        stage('Build & Push Image') {
            steps {
                echo 'Logging in to Docker Hub and Pushing Image...'
                // Sintaks Windows Batch untuk meneruskan token ke perintah docker login
                bat "echo ${env.DOCKER_TOKEN} | docker login -u ${env.DOCKER_notification} --password-stdin"
                bat "docker push ${env.IMAGE_NAME}:latest"
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                echo 'Deploying auth-service to Kubernetes...'
                // Di lokal laptop (Minikube), kalian biasanya tidak perlu 'withKubeConfig' jika kubectl sudah langsung terhubung.
                // Jika demo di Cloud (seperti AKS/GKE), aktifkan baris 'withKubeConfig' di bawah ini dengan menghapus tanda komentar (//)
                
                // withKubeConfig([credentialsId: 'k8s-config']) {
                    bat 'cd /d auth-service && kubectl apply -f auth-k8s.yaml'
                    bat 'kubectl rollout restart deployment auth-service-deployment'
                // }
            }
        }

        stage('Verify Deployment') {
            steps {
                echo 'Verifying deployment status...'
                bat "kubectl rollout status deployment/notification-deployment"
            }
        }
    }

    post {
        success {
            echo 'Pipeline Berhasil Sempurna! Semua stage hijau.'
        }
        failure {
            echo 'Pipeline Gagal. Periksa log di atas untuk melihat letak error.'
        }
    }
}