pipeline {
    agent any

    environment {
        DOCKER_USER = "kelompokdealan"
        GIT_REPO_URL = "https://github.com/shakilaaulia/Dealan.git"
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Checking out source code from GitHub...'
                git branch: 'main', url: "${GIT_REPO_URL}"
            }
        }

        stage('Unit Tests') {
            steps {
                echo 'Running Unit Tests...'
                bat 'cd /d auth-service && go test -v ./service/...'
            }
        }

        stage('Lint/Vet') {
            steps {
                echo 'Running Go Vet...'
                bat 'cd /d auth-service && go vet ./...'
            }
        }

        stage('Docker Login') {
            steps {
                echo 'Logging in to Docker Hub securely...'
                // Pastikan kalian sudah membuat credential dengan ID 'docker-baru' di Jenkins kalian
                withCredentials([usernamePassword(
                    credentialsId: 'docker-baru',
                    usernameVariable: 'D_USER',
                    passwordVariable: 'D_PASS'
                )]) {
                    bat 'docker login -u %D_USER% -p %D_PASS%'
                }
            }
        }

        stage('Build & Push Image') {
            steps {
                echo 'Building and Pushing Auth Service Image...'
                // Menggunakan tanda kutip tiga ganda (""") agar variable Jenkins ${DOCKER_USER} bisa terbaca di perintah Windows bat
                bat """
                cd /d auth-service && docker build -t ${DOCKER_USER}/auth-service:latest .
                docker push ${DOCKER_USER}/auth-service:latest
                """
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                echo 'Deploying auth-service to Kubernetes...'
                // Di lokal laptop (Minikube), kalian biasanya tidak perlu 'withKubeConfig' jika kubectl sudah langsung terhubung.
                // Jika demo di Cloud (seperti AKS/GKE), aktifkan baris 'withKubeConfig' di bawah ini dengan menghapus tanda komentar (//)
                
                // withKubeConfig([credentialsId: 'k8s-config']) {
                    bat 'cd /d auth-service && kubectl apply -f auth-k8s.yaml'
                    bat 'kubectl rollout restart deployment auth-service-deployment'
                // }
            }
        }

        stage('Verify Deployment') {
            steps {
                echo 'Verifying deployment status...'
                bat 'kubectl get pods'
                bat 'kubectl get services'
            }
        }
    }

    post {
        success {
            echo 'Pipeline Berhasil Sempurna! Semua stage hijau.'
        }
        failure {
            echo 'Pipeline Gagal. Periksa log di atas untuk melihat letak error.'
        }
    }
}