name: New Environment
values:
  - key: userToken
    value: ''
    enabled: true
  - key: userId
    value: ''
    enabled: true
  - key: driverId
    value: ''
    enabled: true
  - key: orderId
    value: ''
    enabled: true
  - key: transactionId
    value: ''
    enabled: true
  - key: authBaseUrl
    value: 'http://localhost:3001'
    enabled: true
  - key: driverBaseUrl
    value: 'http://localhost:3003'
    enabled: true
  - key: orderBaseUrl
    value: 'http://localhost:3004'
    enabled: true
  - key: matchingBaseUrl
    value: 'http://localhost:3005'
    enabled: true
  - key: locationBaseUrl
    value: 'http://localhost:3008'
    enabled: true
  - key: mapRouteBaseUrl
    value: 'http://localhost:3009'
    enabled: true
  - key: paymentBaseUrl
    value: 'http://localhost:3010'
    enabled: true
  - key: notificationBaseUrl
    value: 'http://localhost:3011'
    enabled: true
  - key: ratingBaseUrl
    value: 'http://localhost:3012'
    enabled: true
