pipeline {
    agent any

    environment {
        IMAGE_NAME = "shakilaaulia245/map-route-service"
    }

    stages {

        stage('Build Docker Image') {
            steps {
                dir('map-route-service') {
                    sh 'docker build -t $IMAGE_NAME .'
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                sh 'docker push $IMAGE_NAME'
            }
        }

        stage('Run Container') {
            steps {
                sh 'docker stop map-route-service || true'
                sh 'docker rm map-route-service || true'

                sh 'docker run -d --name map-route-service -p 8085:8085 $IMAGE_NAME'
            }
        }
    }
}