pipeline {
    agent any

    environment {
        DOCKER_HUB_USER = 'kelompokdealan'
        DOCKER_HUB_ID   = 'dealan-docker'
        APP_NAME        = 'promo-service'
    }

    stages {

        stage('1. Checkout Code') {
            steps {
                echo 'Checking out source code...'
            }
        }

        stage('2. Unit Tests') {
            steps {
                dir('promo-service') {

                    catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {

                        bat 'go test ./service/...'
                    }
                }
            }
        }

        stage('3. Lint and Vet') {
            steps {
                dir('promo-service') {

                    bat 'go vet ./...'
                }
            }
        }

        stage('4. Build Docker Image') {
            steps {
                dir('promo-service') {

                    bat "docker build -t ${DOCKER_HUB_USER}/${APP_NAME}:latest ."
                }
            }
        }

        stage('5. Functional Tests') {
            steps {
                dir('promo-service') {

                    catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {

                        bat 'go test ./tests/...'
                    }
                }
            }
        }

        stage('6. Push to Docker Hub') {
            steps {

                withCredentials([usernamePassword(credentialsId: "${DOCKER_HUB_ID}", passwordVariable: 'PASS', usernameVariable: 'USER')]) {

                    bat 'echo %PASS%|docker login -u %USER% --password-stdin'

                    bat "docker push ${DOCKER_HUB_USER}/${APP_NAME}:latest"
                }
            }
        }

        stage('7. Deploy to Kubernetes') {
            steps {
                dir('promo-service') {

                    withCredentials([file(credentialsId: 'minikube-dealan', variable: 'KUBECONFIG_FILE')]) {

                        bat 'kubectl --kubeconfig=\"%KUBECONFIG_FILE%\" apply -f promo-service-k8s.yaml --validate=false'
                    }
                }
            }
        }

        stage('8. Verify Deployment') {
            steps {

                withCredentials([file(credentialsId: 'minikube-dealan', variable: 'KUBECONFIG_FILE')]) {

                    bat 'kubectl --kubeconfig=\"%KUBECONFIG_FILE%\" get pods'
                }
            }
        }
    }
}